name: Validate HTML

on: [push, pull_request]

jobs:
  htmlcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install htmlhint
        run: npm install -g htmlhint

      - name: Generate static pages
        run: node build.js

      - name: Validate HTML
        run: htmlhint . --config .htmlhintrc || exit 1
